default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dark
  database: DarkDB
  host: localhost
  port: 5432

development:
  <<: *default
  username: dark
  database: DarkDB
  host: localhost
  port: 5432

test:
  <<: *default
  database: DarkDB_Test
  username: dark
  host: localhost
  port: 5432

